inherit_from: configs/base.yaml
device: cuda
scale: null # Specified in a utils file with other transformations instead of here
dataset: 'ATLAS'
mesh: /home/fsc/max/Data/Pigs/ImFusionExport_abdominal_cavity_coarse.obj
cam:
  H: 540
  W: 960
  fx: 587.36083984375
  fy: 587.36083984375
  cx: 529.1632080078125
  cy: 271.7477111816406

data:
  input_folder: /home/fsc/max/Data/Pigs/dynamic_breathing_half_res
  output: output/ATLAS/

training:
  optical_flow_init: False
  w_depth: 10 # default: 10
  w_color: 5 # default: 5
  w_def:
    w_arap: 0.01

  iters: 200 # default: 100
  iters_first: 1000 # default: 1000

  # TODO: change later when having implemented mesh-based densification
  densify_from_iter: 2000 # default: 100
  densification_interval: 100 # default: 100

  # TODO: Might want to enable this again at some point
  grad_weighing: False # default: Tru