inherit_from: configs/ATLAS/atlas_base.yaml
cam:
  H: 540
  W: 960
  fx: 587.36083984375
  fy: 587.36083984375
  cx: 529.1632080078125
  cy: 271.7477111816406

data:
  image_input_folder: /home/fsc/max/Data/Pigs/trial11/dataset1_resized
  transforms: /home/fsc/max/Data/Pigs/trial11/dataset1_resized/reduced_tranforms_color_seg.json
  mesh: /home/fsc/max/Data/Pigs/trial11/CT/cavity_minimal_cleaned_3.obj
  output: output/ATLAS/trial11_vid08/dataset1
