name: bridgesplat
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- mpmath=1.3.0
- joblib=1.4.2
- openjpeg=2.5.2
- lcms2=2.12
- torchvision=0.20.1
- wheel=0.44.0
- mkl_fft=1.3.11
- gmpy2=2.1.2
- libstdcxx=14.2.0
- mkl_random=1.2.8
- tensorboard=2.18.0
