inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: /home/fsc/max/Data/Synthetic/liver_in
  mesh: /home/fsc/max/Data/Synthetic/liver_in/mesh_0000.obj
  transforms: /home/fsc/max/Data/Synthetic/liver_in/transforms.json
  output: output/SOFA/liver_in