inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: /home/fsc/max/Data/Synthetic/liver_up
  mesh: /home/fsc/max/Data/Synthetic/liver_up/mesh_0000.obj
  transforms: /home/fsc/max/Data/Synthetic/liver_up/transforms.json
  output: output/SOFA/liver_up