inherit_from: configs/base.yaml
device: cuda
scale: 1
dataset: 'NEURO'

cam:
  H: 512
  W: 512
  fx: 955.4050067376327
  fy: 955.4050067376327
  cx: 256
  cy: 256

training:
  optical_flow_init: False
  # TODO: figure this out; should be high but becomes unstable at 10
  w_depth: 10 # default: 10
  w_color: 5 # default: 5
  w_def:
    w_arap: .001 # TODO: figure that out
    w_scale: 100 # TODO: figure that out
  feature_lr: 0.0025 # default: 0.0025
  barycentric_coords_lr: .01

  deformation_lr_init: 0.0025 # default: 0.00016

  iters: 100 # default: 100
  iters_first: 100 # default: 1000

  # TODO: maybe enable again at some point
  densify_from_iter: 100000 # default: 100
  densification_interval: 50 # default: 100
  densify_grad_threshold: 0.001 # default: 0.002

  # TODO: Might want to enable this again at some point
  grad_weighing: False # default: True

model:
  deform: False
  deform_network:
    subsample: 8 # default: 32
    k: 15 # default: 25
  ARAP:
    active: False
    cotangent_weights: False
    CUDA: False
